### ISSUE TITLE
importing DLT is throwing error what needs to be Done?

### ISSUE THREAD

**Issue by nani0097** [bmwcarit/python-dlt#12] opened 2019-09-05 06:30 UTC
>>> from dlt.dlt import DLTMessage

Traceback (most recent call last):
  File "<pyshell#7>", line 1, in <module>
    from dlt.dlt import DLTMessage
  File "C:\Python27\lib\site-packages\dlt-1.0-py2.7.egg\dlt\dlt.py", line 16, in <module>
    from dlt.core import (
  File "C:\Python27\lib\site-packages\dlt-1.0-py2.7.egg\dlt\core\__init__.py", line 9, in <module>
    from dlt.core.core_base import *
  File "C:\Python27\lib\site-packages\dlt-1.0-py2.7.egg\dlt\core\core_base.py", line 7, in <module>
    dltlib = ctypes.cdll.LoadLibrary('libdlt.so.2')
  File "C:\Python27\lib\ctypes\__init__.py", line 444, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found

**Comment by nani0097** [comment] 2019-09-05 06:30
Can some one help us in resolving the issue mentioned above

**Comment by aigarius** [comment] 2019-09-05 07:42
Running this on Windows is not supported by us. One could try adding support by using the "*.dll" name of the libdlt library instead of Linux-specific "*.so.?" name, but if you get any issues after that, we will not be able to help you.

**Comment by aigarius** [comment] 2019-10-08 13:27
Duplicate of issue #1

**Closed by aigarius** 2019-10-08 13:27 UTC
